name: Check

on:
  push:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  check-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install cross
      run: cargo install cross
    - name: Build
      run: cross check --target x86_64-unknown-linux-gnu
  check-windows:
    runs-on: windows-2019
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: cargo check
  check-mac:
    runs-on: macos-11
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: cargo check
