name: Check

on:
  push:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  check-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup cache
      uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
    - name: Install cross
      run: |
        cargo install cross
        rustup component add rustfmt clippy
    - name: Check
      run: cross clippy --target x86_64-unknown-linux-gnu
    - name: Formatting
      run: cross fmt --check
  check-windows:
    runs-on: windows-2019
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup cache
      uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
    - name: Install rustfmt, clippy
      run: rustup component add rustfmt clippy
    - name: Check
      run: cargo clippy
    - name: Formatting
      run: cargo fmt --check
  check-mac:
    runs-on: macos-11
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup cache
      uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
    - name: Install rustfmt, clippy
      run: rustup component add rustfmt clippy
    - name: Check
      run: cargo clippy
    - name: Formatting
      run: cargo fmt --check
